### ISSUE TITLE
Published Euler angles are inconsistent with published quaternion

### ISSUE THREAD

**Issue by bdholt1** [bdholt1/ros2_bno055_sensor#3]
The euler angles available from the BNO055 package through the function `bno055_convert_double_hpr_rad` are exposed in [this branch](https://github.com/bdholt1/ros2_bno055_sensor/tree/publish_euler).

By passing the quaternion output published in /imu/data/orientation through a [splitter node](https://github.com/bdholt1/rpi-quadcopter/tree/main/imu_rpy) that does this

```
Eigen::Quaterniond q(msg->orientation.w, msg->orientation.x, msg->orientation.y, msg->orientation.z);
auto euler = q.toRotationMatrix().eulerAngles(0, 1, 2);
```
we can compare the reported Euler angles from the BNO055 to the values achieved from converting the quaternion.
Starting with yaw, this is a plot when rotating the BNO055 around the Z-axis. We can see that the reported yaw is decreasing but the yaw obtained by converting the quaternion from the BNO055 is increasing. 
![Screenshot from 2021-06-19 21-36-37](https://user-images.githubusercontent.com/937444/122654962-bd5f7e00-d146-11eb-9895-c719839a7c76.png)

We can do the same for roll (slowly rotating the sensor around the X-axis) and here we see that the roll reported from the BNO055 is 0, whereas the roll obtained by converting the quaternion is changing.
![Screenshot from 2021-06-19 21-46-36](https://user-images.githubusercontent.com/937444/122655139-2abfde80-d148-11eb-8c9c-001bab7fe87e.png)

Finally we do the same for pitch (rotating around the Y-axis) and we see that the pitch reported from the BNO055 is 0 but the pitch obtained by converting the quaternion is changing (and actually seems to have a discontinuity at around 45degrees)
![Screenshot from 2021-06-19 21-53-54](https://user-images.githubusercontent.com/937444/122655281-17f9d980-d149-11eb-9cc2-9f68552d1022.png)

Taken together, it does seem that the euler angles reported by the BNO055 are in a different coordinate frame to the quaternion (yaw, is opposite sign, roll and pitch swapped). 

It is possible that this is somehow related to I2C, there is a known problem with the RPi, but you would expect that to result in complete communication failure, rather than this apparent coordinate frame change.

**Comment by traversaro** [comment]
Related ROS Discourse comment: https://discourse.ros.org/t/ros2-bno055-driver/20994/3 .

Related issues:
* https://github.com/robotology/icub-main/issues/701
* https://github.com/robotology/icub-firmware/pull/154

**Comment by bdholt1** [comment]
It seems that there are a few separate things going on here.  Firstly, from the [Adafruit FAQs](https://learn.adafruit.com/adafruit-bno055-absolute-orientation-sensor/faqs)

> Another thing to be aware of is that until the sensor calibrates it has a relative orientation output (i.e. orientation will be relative to where the sensor was when it powered on).

> The Euler angles coming out of the chip are based on 'automatic orientation detection', which has the drawback of not being continuous for all angles and situations. According to Bosch BNO055 Euler angle output should only be used for eCompass, where pitch and roll stay below 45 degrees.

On the Bosch Sensortec community page there was a [similar question](https://community.bosch-sensortec.com/t5/MEMS-sensors-forum/BNO055-data-interpretation/td-p/11863) which pointed to the same thing @traversaro mentioned - the Windows vs Android format.

> BNO055 Euler angle output is configured by the register map : either Windows or Android format. In addition, the BNO055 automatically switches the reference plane automatically wheter it is mounted on the top side or bottom side of the PCB. From your question alone I would highly recommend that you simply forget the BNO055 output altogether. Starting with the quaternions, you can re-calculate the Euler angles in floating point in your host, in the format that you like. 

So it seems that 2 things should happen:
1. Use the quaternion values and convert them at the last minute if required
2. Implement sensor calibration to enable absolute measurements that are calibrated

**Comment by bdholt1** [comment]
I installed the [Rviz imu plugin](http://wiki.ros.org/rviz_imu_plugin) and did some extensive visualisation and it appears that the orientation coming from IMU is indeed correct.  Yawing the IMU results in a rotation around the Z-axis, rolling results in a rotation around the X-axis and pitching results in rotation around the Y-axis. This is all as expected.  

![Screenshot from 2021-06-27 16-16-13](https://user-images.githubusercontent.com/937444/123550032-5e5fc180-d763-11eb-8caa-d6efed0d0042.png)

At this point it no longer matters whether the Euler angles reported by the BNO055 match what is coming from the quaternion, because the quaternion is correct and we can always convert from the quaternion to Euler angles.

**Comment by HusamZain** [comment]
@bdholt1 thank you fro your valuable work.
I have a question, 
 How did you maange to install Rviz imu plugin in ros2 ?
